/* Partie 1 */
CREATE TABLESPACE Abbad_tbs DATAFILE '/home/hamza/Documents/Study/M1/S1/ASGBD/TP/Abbad_tbs.dat' SIZE 5M AUTOEXTEND ON ONLINE;
CREATE TEMPORARY TABLESPACE Abbad_temp_tbs TEMPFILE '/home/hamza/Documents/Study/M1/S1/ASGBD/TP/Abbad_tbs_temp.dat' SIZE 5M AUTOEXTEND ON;
CREATE USER Abbad IDENTIFIED BY AZERTY DEFAULT TABLESPACE Abbad_tbs TEMPORARY TABLESPACE Abbad_temp_tbs;
GRANT ALL PRIVILEGES TO Abbad;

/* Partie 2 */

/* Question 5 */
/* Creation des tables */
CREATE TABLE SERVICE(
CODE_SERVICE NCHAR(3), /* Une chaine de 3 caracteres */
NOM_SERVICE NVARCHAR2(100), /* Une chaine de caracteres de taille variable (max = 100) */
BATIMENT NCHAR, /* Caractere */
DIRECTEUR NUMBER(4,0) /* Un entier de 4 positions */
);

CREATE TABLE CHAMBRE(
CODE_SERVICE NCHAR(3),
NUM_CHAMBRE  NUMBER(3,0),
SURVEILLANT NUMBER(4,0),
NB_LITS NUMBER(2,0)
);

CREATE TABLE EMPLOYE(
NUM_EMP NUMBER(4,0),
NOM_EMP NVARCHAR2(50),
PRENOM_EMP NVARCHAR2(50),
ADRESSE_EMP NVARCHAR2(150),
TEL_EMP NUMBER(10,0)
);

CREATE TABLE MEDECIN(
NUM_MED NUMBER(4,0),
SPECIALITE NVARCHAR2(13) /* Taille maximale de la specialite */
);

CREATE TABLE INFERMIER(
NUM_INF NUMBER(4,0),
CODE_SERVICE NCHAR(3),
ROTATION NCHAR(4), /* JOUR ou NUIT */
SALAIRE NUMBER(10,2)
);

CREATE TABLE PATIENT(
NUM_PATIENT NUMBER(4,0),
NOM_PATIENT NVARCHAR2(50),
PRENOM_PATIENT NVARCHAR2(50),
ADRESSE_PATIENT NVARCHAR2(150),
TEL_PATIENT NUMBER(10,0),
MUTUELLE NVARCHAR2(10)
);

CREATE TABLE HOSPITALISATION(
NUM_PATIENT NUMBER(4,0),
CODE_SERVICE NCHAR(3),
NUM_CHAMBRE  NUMBER(3,0),
LIT NUMBER(2,0)
);

CREATE TABLE SOIGNE(
NUM_PATIENT NUMBER(4,0),
NUM_MED NUMBER(4,0)
);

/* Ajout des contraintes */

/* Les cles primaires et les champs uniques */
ALTER TABLE SERVICE ADD CONSTRAINT PK_SERVICE PRIMARY KEY(CODE_SERVICE);
ALTER TABLE SERVICE ADD CONSTRAINT U_NOM_SERVICE UNIQUE(NOM_SERVICE);
ALTER TABLE CHAMBRE ADD CONSTRAINT PK_CHAMBRE PRIMARY KEY(CODE_SERVICE, NUM_CHAMBRE);
ALTER TABLE EMPLOYE ADD CONSTRAINT PK_EMPLOYE PRIMARY KEY(NUM_EMP);
ALTER TABLE MEDECIN ADD CONSTRAINT PK_MEDECIN PRIMARY KEY(NUM_MED);
ALTER TABLE INFERMIER ADD CONSTRAINT PK_INFERMIER PRIMARY KEY(NUM_INF);
ALTER TABLE PATIENT ADD CONSTRAINT PK_PATIENT PRIMARY KEY(NUM_PATIENT);
ALTER TABLE HOSPITALISATION ADD CONSTRAINT PK_HOSPITALISATION PRIMARY KEY(NUM_PATIENT);
ALTER TABLE HOSPITALISATION ADD CONSTRAINT U_LIT UNIQUE(LIT);
ALTER TABLE SOIGNE ADD CONSTRAINT PK_SOIGNE PRIMARY KEY(NUM_PATIENT, NUM_MED);
/* Les cles etrangeres */
ALTER TABLE SERVICE ADD CONSTRAINT FK_DIRECTEUR FOREIGN KEY(DIRECTEUR) REFERENCES MEDECIN(NUM_MED) ON DELETE SET NULL;
ALTER TABLE CHAMBRE ADD CONSTRAINT FK_SURVEILLANT FOREIGN KEY(SURVEILLANT) REFERENCES INFERMIER(NUM_INF) ON DELETE SET NULL;
ALTER TABLE MEDECIN ADD CONSTRAINT FK_NUM_MED FOREIGN KEY(NUM_MED) REFERENCES EMPLOYE(NUM_EMP) ON DELETE SET NULL;
ALTER TABLE INFERMIER ADD CONSTRAINT FK_NUM_INF FOREIGN KEY(NUM_INF) REFERENCES EMPLOYE(NUM_EMP) ON DELETE SET NULL;
ALTER TABLE INFERMIER ADD CONSTRAINT FK_CODE_SERVICE FOREIGN KEY(CODE_SERVICE) REFERENCES SERVICE(CODE_SERVICE) ON DELETE SET NULL;
ALTER TABLE HOSPITALISATION ADD CONSTRAINT FK_NUM_PATIENT FOREIGN KEY(NUM_PATIENT) REFERENCES PATIENT(NUM_PATIENT) ON DELETE SET NULL;
ALTER TABLE HOSPITALISATION ADD CONSTRAINT FK_CODE_SERVICE_H FOREIGN KEY(CODE_SERVICE) REFERENCES SERVICE(CODE_SERVICE) ON DELETE SET NULL;
ALTER TABLE HOSPITALISATION ADD CONSTRAINT FK_CS_NC FOREIGN KEY(CODE_SERVICE,NUM_CHAMBRE) REFERENCES CHAMBRE(CODE_SERVICE,NUM_CHAMBRE) ON DELETE SET NULL;
/* Les verifications */
ALTER TABLE MEDECIN ADD CONSTRAINT CHK_SPECIALITE CHECK(SPECIALITE IN ('Orthopediste', 'Cardiologue', 'Traumatologue', 'Anesthesiste', 'Pneumologue', 'Radiologue'));
ALTER TABLE INFERMIER ADD CONSTRAINT CHK_ROTATION CHECK(ROTATION IN ('JOUR', 'NUIT'));

/* Question 6 */
ALTER TABLE HOSPITALISATION ADD (DATE_HOST DATE);

/* Question 7 */
ALTER TABLE INFERMIER MODIFY SALAIRE NOT NULL;
ALTER TABLE PATIENT MODIFY MUTUELLE NOT NULL;

/* Question 8 */
ALTER TABLE PATIENT MODIFY PRENOM_PATIENT NVARCHAR2(75);
ALTER TABLE PATIENT MODIFY PRENOM_PATIENT NVARCHAR2(50);

/* Question 9 */
ALTER TABLE EMPLOYE DROP COLUMN TEL_EMP;
DESC EMPLOYE;
ALTER TABLE EMPLOYE ADD TEL_EMP NUMBER(10,0);

/* Question 10 */
ALTER TABLE PATIENT RENAME COLUMN ADRESSE_PATIENT TO adr_pat;
DESC PATIENT;

/* Question 11 */
ALTER TABLE INFERMIER ADD CONSTRAINT CHK_SALAIRE CHECK(SALAIRE BETWEEN 10000 AND 30000);

/* Question 12 */
ALTER TABLE MEDECIN MODIFY SPECIALITE NOT NULL;
